"""add_employee_fields_to_user

Revision ID: 015_add_employee_fields_to_user
Revises: 014_add_one_time_login_tokens
Create Date: 2026-06-16 22:27:15.444834
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '015_add_employee_fields_to_user'
down_revision: Union[str, None] = '014_add_one_time_login_tokens'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tab_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['tab_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'department')
    op.drop_column('users', 'position')
    op.drop_column('users', 'tab_number')
    # ### end Alembic commands ###
