"""add_hrms_employee_id_to_user

Revision ID: cf9ec5b8d6b5
Revises: 016_add_hrms_access_level
Create Date: 2026-06-17 17:58:15.045677
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'cf9ec5b8d6b5'
down_revision: Union[str, None] = '016_add_hrms_access_level'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('techcard_pair_lines')
    op.drop_table('techcard_pairs')
    op.drop_index('ix_route_signature_rules_lookup', table_name='route_signature_rules')
    op.drop_table('route_signature_rules')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_lookup', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_section_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_entity_comments_entity', table_name='entity_comments')
    op.drop_index('ix_movements_performed_at', table_name='movements')
    op.drop_index('ix_movements_task_created_at', table_name='movements')
    op.drop_index('ix_plan_positions_deleted_at', table_name='plan_positions', postgresql_where='(deleted_at IS NOT NULL)')
    op.drop_constraint('processing_flags_code_key', 'processing_flags', type_='unique')
    op.create_index(op.f('ix_processing_flags_code'), 'processing_flags', ['code'], unique=True)
    op.drop_index('ix_product_lengths_product_id', table_name='product_lengths')
    op.drop_constraint('uq_product_lengths_product_length', 'product_lengths', type_='unique')
    op.drop_index('ix_product_processing_flags_product_id', table_name='product_processing_flags')
    op.drop_constraint('uq_product_flags_product_flag', 'product_processing_flags', type_='unique')
    op.alter_column('route_matching_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('route_rule_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('route_selection_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_route_selection_rules_active_profile_phase_priority', table_name='route_selection_rules')
    op.drop_index('ix_route_selection_rules_priority', table_name='route_selection_rules')
    op.alter_column('section_operations', 'section_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index('ix_spg_remainders_active', table_name='spg_remainders', postgresql_where='(consumed_at IS NULL)')
    op.drop_index('ix_spg_remainders_product', table_name='spg_remainders')
    op.drop_index('ix_spg_remainders_reserved_plan_pos', table_name='spg_remainders')
    op.drop_index('ix_spg_remainders_spg', table_name='spg_remainders')
    op.drop_index('ix_warehouse_remainders_created_by', table_name='spg_remainders')
    op.drop_constraint('uq_spg_sections_section_id', 'spg_sections', type_='unique')
    op.drop_index('ix_storage_production_groups_storage_kind', table_name='storage_production_groups')
    op.drop_index('ix_techcards_product_id', table_name='techcards')
    op.drop_index('ix_user_login_tokens_token', table_name='user_login_tokens')
    op.add_column('users', sa.Column('hrms_employee_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('users_tab_number_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['hrms_employee_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_tab_number_key', 'users', ['tab_number'])
    op.drop_column('users', 'hrms_employee_id')
    op.create_index('ix_user_login_tokens_token', 'user_login_tokens', ['token'], unique=False)
    op.create_index('ix_techcards_product_id', 'techcards', ['product_id'], unique=False)
    op.create_index('ix_storage_production_groups_storage_kind', 'storage_production_groups', ['storage_kind'], unique=False)
    op.create_unique_constraint('uq_spg_sections_section_id', 'spg_sections', ['section_id'])
    op.create_index('ix_warehouse_remainders_created_by', 'spg_remainders', ['created_by'], unique=False)
    op.create_index('ix_spg_remainders_spg', 'spg_remainders', ['spg_id'], unique=False)
    op.create_index('ix_spg_remainders_reserved_plan_pos', 'spg_remainders', ['reserved_for_plan_position_id'], unique=False)
    op.create_index('ix_spg_remainders_product', 'spg_remainders', ['product_id'], unique=False)
    op.create_index('ix_spg_remainders_active', 'spg_remainders', ['spg_id', 'product_id'], unique=False, postgresql_where='(consumed_at IS NULL)')
    op.alter_column('section_operations', 'section_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index('ix_route_selection_rules_priority', 'route_selection_rules', ['priority', 'id'], unique=False)
    op.create_index('ix_route_selection_rules_active_profile_phase_priority', 'route_selection_rules', ['is_active', 'profile_id', 'phase', 'priority'], unique=False)
    op.alter_column('route_selection_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('route_rule_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('route_matching_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_product_flags_product_flag', 'product_processing_flags', ['product_id', 'flag_id'])
    op.create_index('ix_product_processing_flags_product_id', 'product_processing_flags', ['product_id'], unique=False)
    op.create_unique_constraint('uq_product_lengths_product_length', 'product_lengths', ['product_id', 'length_mm'])
    op.create_index('ix_product_lengths_product_id', 'product_lengths', ['product_id'], unique=False)
    op.drop_index(op.f('ix_processing_flags_code'), table_name='processing_flags')
    op.create_unique_constraint('processing_flags_code_key', 'processing_flags', ['code'])
    op.create_index('ix_plan_positions_deleted_at', 'plan_positions', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NOT NULL)')
    op.create_index('ix_movements_task_created_at', 'movements', ['task_id', 'created_at'], unique=False)
    op.create_index('ix_movements_performed_at', 'movements', ['performed_at'], unique=False)
    op.create_index('ix_entity_comments_entity', 'entity_comments', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_section_id', 'audit_logs', ['section_id'], unique=False)
    op.create_index('ix_audit_logs_entity_type', 'audit_logs', ['entity_type'], unique=False)
    op.create_index('ix_audit_logs_entity_lookup', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_id', 'audit_logs', ['entity_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_table('route_signature_rules',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('has_pack_ops', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['production_routes.id'], name='route_signature_rules_route_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='route_signature_rules_pkey')
    )
    op.create_index('ix_route_signature_rules_lookup', 'route_signature_rules', ['has_pack_ops', 'is_active', 'priority'], unique=False)
    op.create_table('techcard_pairs',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('techcard_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('priority', sa.BIGINT(), server_default=sa.text('100'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['techcard_id'], ['techcards.id'], name='techcard_pairs_techcard_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='techcard_pairs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('techcard_pair_lines',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('techcard_pair_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('component_product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=14, scale=3), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_product_id'], ['products.id'], name='techcard_pair_lines_component_product_id_fkey'),
    sa.ForeignKeyConstraint(['techcard_pair_id'], ['techcard_pairs.id'], name='techcard_pair_lines_techcard_pair_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='techcard_pair_lines_pkey'),
    sa.UniqueConstraint('techcard_pair_id', 'component_product_id', name='uq_techcard_pair_lines_component')
    )
    # ### end Alembic commands ###
