"""initial_baseline

Revision ID: 231b7895bf40
Revises: 
Create Date: 2026-05-03 14:41:04.442417
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '231b7895bf40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_files',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_path', sa.String(length=1000), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('file_extension', sa.String(length=20), nullable=False),
    sa.Column('detected_format', sa.String(length=50), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_sha256')
    )
    op.create_table('production_plans',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('plan_no', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'validated', 'approved', 'partially_released', 'released', 'cancelled', name='production_plan_status'), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_no')
    )
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('finished_good', 'semi_finished', 'component', 'material', name='product_type'), nullable=False),
    sa.Column('unit', sa.String(length=50), server_default=sa.text("'pcs'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('profile_type', sa.String(length=100), nullable=True),
    sa.Column('alloy', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('anod_type', sa.String(length=50), nullable=True),
    sa.Column('length_mm', sa.Float(), nullable=True),
    sa.Column('weight_per_meter', sa.Float(), nullable=True),
    sa.Column('quantity_per_hanger', sa.Integer(), nullable=True),
    sa.Column('cross_section', sa.String(length=100), nullable=True),
    sa.Column('photo_thumb', sa.String(length=500), nullable=True),
    sa.Column('photo_full', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('is_catalog_item', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_paired_profile', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_alloy'), 'products', ['alloy'], unique=False)
    op.create_index(op.f('ix_products_color'), 'products', ['color'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_profile_type'), 'products', ['profile_type'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_source'), 'products', ['source'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('kind', sa.String(length=20), server_default=sa.text("'production'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('techcards',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('processing_type', sa.String(length=50), server_default=sa.text("'standart_processing'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_techcards_active_one_per_product', 'techcards', ['product_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('import_batches',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('source_file_id', sa.BigInteger(), nullable=False),
    sa.Column('production_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('mode', sa.Enum('create_plan', 'append_to_plan', 'replace_draft_from_same_source', name='import_batch_mode'), nullable=False),
    sa.Column('status', sa.Enum('parsed', 'failed', 'applied', 'cancelled', name='import_batch_status'), server_default=sa.text("'parsed'"), nullable=False),
    sa.Column('source_system', sa.String(length=100), server_default=sa.text("'excel'"), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=False),
    sa.Column('header_row_number', sa.BigInteger(), nullable=False),
    sa.Column('total_rows', sa.BigInteger(), nullable=False),
    sa.Column('parsed_rows', sa.BigInteger(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_plan_id'], ['production_plans.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['import_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_routes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('route_matching_rules',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('route_id', sa.BigInteger(), sa.ForeignKey('production_routes.id'), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_rule_conditions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), sa.ForeignKey('route_matching_rules.id'), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'planner', 'section_manager', 'operator', 'viewer', name='user_role'), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('techcard_lines',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('techcard_id', sa.BigInteger(), nullable=False),
    sa.Column('component_product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['techcard_id'], ['techcards.id'], ),
    sa.ForeignKeyConstraint(['component_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('techcard_id', 'component_product_id', name='uq_techcard_lines_component')
    )
    op.create_table('import_templates',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_change_sets',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('production_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('import_batch_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'applied', 'cancelled', name='plan_change_set_status'), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['production_plan_id'], ['production_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_positions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('production_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.Enum('manual', 'excel_import', 'api', 'integration', name='plan_source_type'), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('external_plan_id', sa.String(length=255), nullable=True),
    sa.Column('source_row_hash', sa.String(length=64), nullable=True),
    sa.Column('import_batch_id', sa.BigInteger(), nullable=True),
    sa.Column('source_sku', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.String(length=1000), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('source_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.BigInteger(), server_default=sa.text('100'), nullable=False),
    sa.Column('source_row_number', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'invalid', 'valid', 'approved', 'released', 'cancelled', name='plan_position_status'), nullable=False),
    sa.Column('validation_status', sa.Enum('pending', 'valid', 'invalid', name='plan_position_validation_status'), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['production_plan_id'], ['production_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plan_positions_import_hash', 'plan_positions', ['import_batch_id', 'source_row_hash'], unique=True)
    op.create_index('ix_plan_positions_import_row', 'plan_positions', ['import_batch_id', 'source_row_number'], unique=True)
    op.create_table('release_batches',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('batch_no', sa.String(length=100), nullable=False),
    sa.Column('production_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('batch_type', sa.Enum('near_term', 'weekly', 'future_preparation', 'manual', name='release_batch_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'released', 'cancelled', name='release_batch_status'), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('horizon_start', sa.Date(), nullable=True),
    sa.Column('horizon_end', sa.Date(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_by', sa.BigInteger(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['production_plan_id'], ['production_plans.id'], ),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_no')
    )
    op.create_table('route_steps',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.Column('operation_code', sa.String(length=100), nullable=True),
    sa.Column('operation_name', sa.String(length=255), nullable=False),
    sa.Column('norm_time_minutes', sa.Integer(), nullable=True),
    sa.Column('requires_acceptance', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('allow_parallel', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_final', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['production_routes.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'sequence', name='uq_route_steps_sequence')
    )
    op.create_table('internal_plans',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('production_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('release_batch_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('active', 'cancelled', 'completed', name='internal_plan_status'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_plan_id'], ['production_plans.id'], ),
    sa.ForeignKeyConstraint(['release_batch_id'], ['release_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_internal_plans_release_batch', 'internal_plans', ['release_batch_id'], unique=True)
    op.create_table('plan_change_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('change_set_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_position_id', sa.BigInteger(), nullable=True),
    sa.Column('source_row_number', sa.BigInteger(), nullable=True),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('change_action', sa.Enum('create_position', 'update_draft_position', 'mark_possible_duplicate', 'ignore_unchanged', 'cancel_draft_position', name='plan_change_action'), nullable=False),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'warning', 'invalid', 'applied', name='plan_change_item_status'), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['change_set_id'], ['plan_change_sets.id'], ),
    sa.ForeignKeyConstraint(['plan_position_id'], ['plan_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plan_change_items_change_set', 'plan_change_items', ['change_set_id'], unique=False)
    op.create_table('release_batch_positions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('release_batch_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_position_id', sa.BigInteger(), nullable=False),
    sa.Column('release_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False),
    sa.Column('route_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['plan_position_id'], ['plan_positions.id'], ),
    sa.ForeignKeyConstraint(['release_batch_id'], ['release_batches.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['production_routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('release_batch_id', 'plan_position_id', name='uq_release_batch_position')
    )
    op.create_table('section_plan_lines',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('internal_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_position_id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False),
    sa.Column('route_step_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('planned_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('cached_available_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('cached_issued_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('cached_completed_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('cached_transferred_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('cached_received_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('cached_rejected_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('cached_remaining_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['internal_plan_id'], ['internal_plans.id'], ),
    sa.ForeignKeyConstraint(['plan_position_id'], ['plan_positions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['production_routes.id'], ),
    sa.ForeignKeyConstraint(['route_step_id'], ['route_steps.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_plan_id', 'plan_position_id', 'route_step_id', name='uq_section_plan_lines_step')
    )
    op.create_table('work_tasks',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('section_plan_line_id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('route_step_id', sa.BigInteger(), nullable=False),
    sa.Column('planned_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('status', sa.Enum('waiting_previous', 'ready', 'in_progress', 'completed', 'cancelled', name='work_task_status'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('assigned_to', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cached_available_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('cached_issued_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('cached_in_work_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('cached_completed_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('cached_transferred_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('cached_received_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('cached_rejected_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('cached_remaining_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['route_step_id'], ['route_steps.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['section_plan_line_id'], ['section_plan_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_tasks')
    op.drop_table('section_plan_lines')
    op.drop_table('release_batch_positions')
    op.drop_index('ix_plan_change_items_change_set', table_name='plan_change_items')
    op.drop_table('plan_change_items')
    op.drop_index('ix_internal_plans_release_batch', table_name='internal_plans')
    op.drop_table('internal_plans')
    op.drop_table('route_steps')
    op.drop_table('release_batches')
    op.drop_index('ix_plan_positions_import_row', table_name='plan_positions')
    op.drop_index('ix_plan_positions_import_hash', table_name='plan_positions')
    op.drop_table('plan_positions')
    op.drop_table('plan_change_sets')
    op.drop_table('import_templates')
    op.drop_table('techcard_lines')
    op.drop_table('users')
    op.drop_table('route_rule_conditions')
    op.drop_table('route_matching_rules')
    op.drop_table('production_routes')
    op.drop_table('import_batches')
    op.drop_index('ix_techcards_active_one_per_product', table_name='techcards', postgresql_where=sa.text('is_active = true'))
    op.drop_table('techcards')
    op.drop_table('sections')
    op.drop_index(op.f('ix_products_source'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_profile_type'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_color'), table_name='products')
    op.drop_index(op.f('ix_products_alloy'), table_name='products')
    op.drop_table('products')
    op.drop_table('production_plans')
    op.drop_table('import_files')
    # ### end Alembic commands ###
