from __future__ import annotations

ROUTES = [
    {
        "code": "fg_drill_shot",
        "name": "ГП • Сверло",
        "description": "WH → DRILL → SHOT → ANOD → WIP_WH → SAW → PACK / PACK_STRETCH → FG_WH → SHIPMENT → SENT",
        "sort_order": 10,
        "steps": [
            {"section_code": "WH", "operation_code": "ISSUE_RAW", "operation_name": "Выдача сырья"},
            {"section_code": "DRILL", "operation_code": "DRILL", "operation_name": "Сверловка"},
            {"section_code": "SHOT", "operation_code": "SHOT", "operation_name": "Дробеструй"},
            {"section_code": "ANOD", "operation_code": None, "operation_name": "Анодирование", "combined_op_group": "anod_pack"},
            {"section_code": "ANOD", "operation_code": "PACK_STRETCH", "operation_name": "Стрейч", "combined_op_group": "anod_pack"},
            {"section_code": "WIP_WH", "operation_code": "MOVE_TO_WIP", "operation_name": "Передача на склад полуфабриката"},
            {"section_code": "SAW", "operation_code": "SAW", "operation_name": "Резка на пиле"},
            {"section_code": "PACK", "operation_code": "PACK", "operation_name": "Упаковка"},
            {"section_code": "FG_WH", "operation_code": "FG_WH", "operation_name": "Склад готовой продукции"},
            {"section_code": "SHIPMENT", "operation_code": "SHIPMENT", "operation_name": "К отгрузке"},
            {"section_code": "SENT", "operation_code": "SENT", "operation_name": "Отправлено", "is_final": True},
        ],
    },
    {
        "code": "fg_press_shot",
        "name": "ГП • Пресс",
        "description": "WH → PRESS → SHOT → ANOD → WIP_WH → SAW → PACK / PACK_STRETCH → FG_WH → SHIPMENT → SENT",
        "sort_order": 20,
        "steps": [
            {"section_code": "WH", "operation_code": "ISSUE_RAW", "operation_name": "Выдача сырья"},
            {"section_code": "PRESS", "operation_code": None, "operation_name": "Пресс"},
            {"section_code": "SHOT", "operation_code": "SHOT", "operation_name": "Дробеструй"},
            {"section_code": "ANOD", "operation_code": None, "operation_name": "Анодирование", "combined_op_group": "anod_pack"},
            {"section_code": "ANOD", "operation_code": "PACK_STRETCH", "operation_name": "Стрейч", "combined_op_group": "anod_pack"},
            {"section_code": "WIP_WH", "operation_code": "MOVE_TO_WIP", "operation_name": "Передача на склад полуфабриката"},
            {"section_code": "SAW", "operation_code": "SAW", "operation_name": "Резка на пиле"},
            {"section_code": "PACK", "operation_code": "PACK", "operation_name": "Упаковка"},
            {"section_code": "FG_WH", "operation_code": "FG_WH", "operation_name": "Склад готовой продукции"},
            {"section_code": "SHIPMENT", "operation_code": "SHIPMENT", "operation_name": "К отгрузке"},
            {"section_code": "SENT", "operation_code": "SENT", "operation_name": "Отправлено", "is_final": True},
        ],
    },
    {
        "code": "fg_primary_none_shot",
        "name": "ГП",
        "description": "WH → SHOT → ANOD → WIP_WH → SAW → PACK / PACK_STRETCH → FG_WH → SHIPMENT → SENT",
        "sort_order": 30,
        "steps": [
            {"section_code": "WH", "operation_code": "ISSUE_RAW", "operation_name": "Выдача сырья"},
            {"section_code": "SHOT", "operation_code": "SHOT", "operation_name": "Дробеструй"},
            {"section_code": "ANOD", "operation_code": None, "operation_name": "Анодирование", "combined_op_group": "anod_pack"},
            {"section_code": "ANOD", "operation_code": "PACK_STRETCH", "operation_name": "Стрейч", "combined_op_group": "anod_pack"},
            {"section_code": "WIP_WH", "operation_code": "MOVE_TO_WIP", "operation_name": "Передача на склад полуфабриката"},
            {"section_code": "SAW", "operation_code": "SAW", "operation_name": "Резка на пиле"},
            {"section_code": "PACK", "operation_code": "PACK", "operation_name": "Упаковка"},
            {"section_code": "FG_WH", "operation_code": "FG_WH", "operation_name": "Склад готовой продукции"},
            {"section_code": "SHIPMENT", "operation_code": "SHIPMENT", "operation_name": "К отгрузке"},
            {"section_code": "SENT", "operation_code": "SENT", "operation_name": "Отправлено", "is_final": True},
        ],
    },
    {
        "code": "fg_drill_no_shot",
        "name": "ГП • Сверло • Без дробеструя",
        "description": "WH → DRILL → ANOD → WIP_WH → SAW → PACK / PACK_STRETCH → FG_WH → SHIPMENT → SENT",
        "sort_order": 40,
        "steps": [
            {"section_code": "WH", "operation_code": "ISSUE_RAW", "operation_name": "Выдача сырья"},
            {"section_code": "DRILL", "operation_code": "DRILL", "operation_name": "Сверловка"},
            {"section_code": "ANOD", "operation_code": None, "operation_name": "Анодирование", "combined_op_group": "anod_pack"},
            {"section_code": "ANOD", "operation_code": "PACK_STRETCH", "operation_name": "Стрейч", "combined_op_group": "anod_pack"},
            {"section_code": "WIP_WH", "operation_code": "MOVE_TO_WIP", "operation_name": "Передача на склад полуфабриката"},
            {"section_code": "SAW", "operation_code": "SAW", "operation_name": "Резка на пиле"},
            {"section_code": "PACK", "operation_code": "PACK", "operation_name": "Упаковка"},
            {"section_code": "FG_WH", "operation_code": "FG_WH", "operation_name": "Склад готовой продукции"},
            {"section_code": "SHIPMENT", "operation_code": "SHIPMENT", "operation_name": "К отгрузке"},
            {"section_code": "SENT", "operation_code": "SENT", "operation_name": "Отправлено", "is_final": True},
        ],
    },
    {
        "code": "fg_press_no_shot",
        "name": "ГП • Пресс • Без дробеструя",
        "description": "WH → PRESS → ANOD → WIP_WH → SAW → PACK / PACK_STRETCH → FG_WH → SHIPMENT → SENT",
        "sort_order": 50,
        "steps": [
            {"section_code": "WH", "operation_code": "ISSUE_RAW", "operation_name": "Выдача сырья"},
            {"section_code": "PRESS", "operation_code": None, "operation_name": "Пресс"},
            {"section_code": "ANOD", "operation_code": None, "operation_name": "Анодирование", "combined_op_group": "anod_pack"},
            {"section_code": "ANOD", "operation_code": "PACK_STRETCH", "operation_name": "Стрейч", "combined_op_group": "anod_pack"},
            {"section_code": "WIP_WH", "operation_code": "MOVE_TO_WIP", "operation_name": "Передача на склад полуфабриката"},
            {"section_code": "SAW", "operation_code": "SAW", "operation_name": "Резка на пиле"},
            {"section_code": "PACK", "operation_code": "PACK", "operation_name": "Упаковка"},
            {"section_code": "FG_WH", "operation_code": "FG_WH", "operation_name": "Склад готовой продукции"},
            {"section_code": "SHIPMENT", "operation_code": "SHIPMENT", "operation_name": "К отгрузке"},
            {"section_code": "SENT", "operation_code": "SENT", "operation_name": "Отправлено", "is_final": True},
        ],
    },
    {
        "code": "fg_primary_none_no_shot",
        "name": "ГП • Без первичной • Без дробеструя",
        "description": "WH → ANOD → WIP_WH → SAW → PACK / PACK_STRETCH → FG_WH → SHIPMENT → SENT",
        "sort_order": 60,
        "steps": [
            {"section_code": "WH", "operation_code": "ISSUE_RAW", "operation_name": "Выдача сырья"},
            {"section_code": "ANOD", "operation_code": None, "operation_name": "Анодирование", "combined_op_group": "anod_pack"},
            {"section_code": "ANOD", "operation_code": "PACK_STRETCH", "operation_name": "Стрейч", "combined_op_group": "anod_pack"},
            {"section_code": "WIP_WH", "operation_code": "MOVE_TO_WIP", "operation_name": "Передача на склад полуфабриката"},
            {"section_code": "SAW", "operation_code": "SAW", "operation_name": "Резка на пиле"},
            {"section_code": "PACK", "operation_code": "PACK", "operation_name": "Упаковка"},
            {"section_code": "FG_WH", "operation_code": "FG_WH", "operation_name": "Склад готовой продукции"},
            {"section_code": "SHIPMENT", "operation_code": "SHIPMENT", "operation_name": "К отгрузке"},
            {"section_code": "SENT", "operation_code": "SENT", "operation_name": "Отправлено", "is_final": True},
        ],
    },
    {
        "code": "sf_drill_shot",
        "name": "П/ф • Сверло",
        "description": "WH → DRILL → SHOT → ANOD → PACK_SPUNBOND → FG_WH → SHIPMENT → SENT",
        "sort_order": 70,
        "steps": [
            {"section_code": "WH", "operation_code": "ISSUE_RAW", "operation_name": "Выдача сырья"},
            {"section_code": "DRILL", "operation_code": "DRILL", "operation_name": "Сверловка"},
            {"section_code": "SHOT", "operation_code": "SHOT", "operation_name": "Дробеструй"},
            {"section_code": "ANOD", "operation_code": None, "operation_name": "Анодирование", "combined_op_group": "anod_spunbond"},
            {"section_code": "ANOD", "operation_code": "PACK_SPUNBOND", "operation_name": "Спанбонд", "combined_op_group": "anod_spunbond"},
            {"section_code": "FG_WH", "operation_code": "FG_WH", "operation_name": "Склад готовой продукции"},
            {"section_code": "SHIPMENT", "operation_code": "SHIPMENT", "operation_name": "К отгрузке"},
            {"section_code": "SENT", "operation_code": "SENT", "operation_name": "Отправлено", "is_final": True},
        ],
    },
    {
        "code": "sf_press_shot",
        "name": "П/ф • Пресс",
        "description": "WH → PRESS → SHOT → ANOD → PACK_SPUNBOND → FG_WH → SHIPMENT → SENT",
        "sort_order": 80,
        "steps": [
            {"section_code": "WH", "operation_code": "ISSUE_RAW", "operation_name": "Выдача сырья"},
            {"section_code": "PRESS", "operation_code": None, "operation_name": "Пресс"},
            {"section_code": "SHOT", "operation_code": "SHOT", "operation_name": "Дробеструй"},
            {"section_code": "ANOD", "operation_code": None, "operation_name": "Анодирование", "combined_op_group": "anod_spunbond"},
            {"section_code": "ANOD", "operation_code": "PACK_SPUNBOND", "operation_name": "Спанбонд", "combined_op_group": "anod_spunbond"},
            {"section_code": "FG_WH", "operation_code": "FG_WH", "operation_name": "Склад готовой продукции"},
            {"section_code": "SHIPMENT", "operation_code": "SHIPMENT", "operation_name": "К отгрузке"},
            {"section_code": "SENT", "operation_code": "SENT", "operation_name": "Отправлено", "is_final": True},
        ],
    },
    {
        "code": "sf_primary_none_shot",
        "name": "П/ф",
        "description": "WH → SHOT → ANOD → PACK_SPUNBOND → FG_WH → SHIPMENT → SENT",
        "sort_order": 90,
        "steps": [
            {"section_code": "WH", "operation_code": "ISSUE_RAW", "operation_name": "Выдача сырья"},
            {"section_code": "SHOT", "operation_code": "SHOT", "operation_name": "Дробеструй"},
            {"section_code": "ANOD", "operation_code": None, "operation_name": "Анодирование", "combined_op_group": "anod_spunbond"},
            {"section_code": "ANOD", "operation_code": "PACK_SPUNBOND", "operation_name": "Спанбонд", "combined_op_group": "anod_spunbond"},
            {"section_code": "FG_WH", "operation_code": "FG_WH", "operation_name": "Склад готовой продукции"},
            {"section_code": "SHIPMENT", "operation_code": "SHIPMENT", "operation_name": "К отгрузке"},
            {"section_code": "SENT", "operation_code": "SENT", "operation_name": "Отправлено", "is_final": True},
        ],
    },
    {
        "code": "sf_drill_no_shot",
        "name": "П/ф • Сверло • Без дробеструя",
        "description": "WH → DRILL → ANOD → PACK_SPUNBOND → FG_WH → SHIPMENT → SENT",
        "sort_order": 100,
        "steps": [
            {"section_code": "WH", "operation_code": "ISSUE_RAW", "operation_name": "Выдача сырья"},
            {"section_code": "DRILL", "operation_code": "DRILL", "operation_name": "Сверловка"},
            {"section_code": "ANOD", "operation_code": None, "operation_name": "Анодирование", "combined_op_group": "anod_spunbond"},
            {"section_code": "ANOD", "operation_code": "PACK_SPUNBOND", "operation_name": "Спанбонд", "combined_op_group": "anod_spunbond"},
            {"section_code": "FG_WH", "operation_code": "FG_WH", "operation_name": "Склад готовой продукции"},
            {"section_code": "SHIPMENT", "operation_code": "SHIPMENT", "operation_name": "К отгрузке"},
            {"section_code": "SENT", "operation_code": "SENT", "operation_name": "Отправлено", "is_final": True},
        ],
    },
    {
        "code": "sf_press_no_shot",
        "name": "П/ф • Пресс • Без дробеструя",
        "description": "WH → PRESS → ANOD → PACK_SPUNBOND → FG_WH → SHIPMENT → SENT",
        "sort_order": 110,
        "steps": [
            {"section_code": "WH", "operation_code": "ISSUE_RAW", "operation_name": "Выдача сырья"},
            {"section_code": "PRESS", "operation_code": None, "operation_name": "Пресс"},
            {"section_code": "ANOD", "operation_code": None, "operation_name": "Анодирование", "combined_op_group": "anod_spunbond"},
            {"section_code": "ANOD", "operation_code": "PACK_SPUNBOND", "operation_name": "Спанбонд", "combined_op_group": "anod_spunbond"},
            {"section_code": "FG_WH", "operation_code": "FG_WH", "operation_name": "Склад готовой продукции"},
            {"section_code": "SHIPMENT", "operation_code": "SHIPMENT", "operation_name": "К отгрузке"},
            {"section_code": "SENT", "operation_code": "SENT", "operation_name": "Отправлено", "is_final": True},
        ],
    },
    {
        "code": "sf_primary_none_no_shot",
        "name": "П/ф • Без первичной • Без дробеструя",
        "description": "WH → ANOD → PACK_SPUNBOND → FG_WH → SHIPMENT → SENT",
        "sort_order": 120,
        "steps": [
            {"section_code": "WH", "operation_code": "ISSUE_RAW", "operation_name": "Выдача сырья"},
            {"section_code": "ANOD", "operation_code": None, "operation_name": "Анодирование", "combined_op_group": "anod_spunbond"},
            {"section_code": "ANOD", "operation_code": "PACK_SPUNBOND", "operation_name": "Спанбонд", "combined_op_group": "anod_spunbond"},
            {"section_code": "FG_WH", "operation_code": "FG_WH", "operation_name": "Склад готовой продукции"},
            {"section_code": "SHIPMENT", "operation_code": "SHIPMENT", "operation_name": "К отгрузке"},
            {"section_code": "SENT", "operation_code": "SENT", "operation_name": "Отправлено", "is_final": True},
        ],
    },
]
