SPGS_DATA = [
    {
        "code": "STOCK",
        "name": "Склад",
        "description": "Склад сырья — все остатки и наличие",
        "sort_order": 10,
        "icon": "Warehouse",
        "icon_color": "#F59E0B",
        "section_codes": ["RAW_STOCK"],
    },
    {
        "code": "PREP",
        "name": "Подготовка",
        "description": "Участки подготовки: сверловка, пресс, дробеструй; складской остаток между этапами подготовки и анодирования",
        "storage_kind": "wip",
        "sort_order": 20,
        "icon": "Wrench",
        "icon_color": "#3B82F6",
        "section_codes": ["DRILLING", "PRESSING", "SHOT_BLAST", "PREP_STOCK"],
    },
    {
        "code": "ANODIZING",
        "name": "Анодирование",
        "description": "Участок анодирования и склад полуфабриката (wip-секция WIP_WH)",
        "storage_kind": "wip",
        "sort_order": 30,
        "icon": "FlaskConical",
        "icon_color": "#06B6D4",
        "section_codes": ["ANODIZING", "WIP_STOCK"],
    },
    {
        "code": "PACKING",
        "name": "Упаковка",
        "description": "Резка и упаковка",
        "sort_order": 50,
        "icon": "Package",
        "icon_color": "#10B981",
        "section_codes": ["SAWING", "PACKING"],
    },
    {
        "code": "FG",
        "name": "Склад готовой продукции",
        "description": "Склад ГП, отгрузка, отправлено",
        "sort_order": 60,
        "icon": "Container",
        "icon_color": "#065F46",
        "section_codes": ["FINISHED_STOCK", "SHIPMENT", "SHIPPED"],
    },
]
