SPGS_DATA = [
    {
        "code": "STOCK",
        "name": "Склад",
        "description": "Склад сырья — все остатки и наличие",
        "sort_order": 10,
        "icon": "Warehouse",
        "icon_color": "#F59E0B",
        "section_codes": ["WH"],
    },
    {
        "code": "PREP",
        "name": "Подготовка",
        "description": "Участки подготовки: сверловка, пресс, дробеструй",
        "sort_order": 20,
        "icon": "Wrench",
        "icon_color": "#3B82F6",
        "section_codes": ["DRILL", "PRESS", "SHOT"],
    },
    {
        "code": "PREP_STOCK",
        "name": "Склад подготовки",
        "description": "Промежуточный склад между этапами подготовки и анодирования",
        "storage_kind": "wip",
        "sort_order": 25,
        "icon": "PackageX",
        "icon_color": "#7C3AED",
        "section_codes": [],
    },
    {
        "code": "ANOD",
        "name": "Анодирование",
        "description": "Участок анодирования",
        "sort_order": 30,
        "icon": "FlaskConical",
        "icon_color": "#06B6D4",
        "section_codes": ["ANOD"],
    },
    {
        "code": "WIP",
        "name": "Склад полуфабриката",
        "description": "Промежуточный склад полуфабриката (sectionless, без привязки к секциям)",
        "storage_kind": "wip",
        "sort_order": 40,
        "icon": "Layers",
        "icon_color": "#65A30D",
        "section_codes": [],
    },
    {
        "code": "PACK",
        "name": "Упаковка",
        "description": "Резка и упаковка",
        "sort_order": 50,
        "icon": "Package",
        "icon_color": "#10B981",
        "section_codes": ["SAW", "PACK"],
    },
    {
        "code": "FG",
        "name": "Склад готовой продукции",
        "description": "Склад ГП, отгрузка, отправлено",
        "sort_order": 60,
        "icon": "Container",
        "icon_color": "#065F46",
        "section_codes": ["FG_WH", "SHIPMENT", "SENT"],
    },
]
