// GENERATED FILE — do not edit by hand. Regenerate: python scripts/generate_frontend_labels.py

// Лейблы статусов позиции плана
export const statusLabels: Record<string, string> = {
  "applied": "Применён",
  "approved": "Утверждён",
  "cancelled": "Отменён",
  "completed": "Завершён",
  "draft": "Черновик",
  "failed": "Ошибка",
  "invalid": "Ошибка",
  "parsed": "Распознан",
  "pending": "Ожидает",
  "released": "Запущен",
  "valid": "Валиден",
  "warning": "Предупреждение",
}

// Лейблы видов выпуска
export const outputKindLabels: Record<string, string> = {
  "finished_good": "Готовая продукция",
  "semi_finished_shipment": "Полуфабрикат",
  "ГП": "Готовая продукция",
  "П/ф": "Полуфабрикат",
}

// Тексты ошибок валидации (ключи — error codes сервера)
export const errorLabels: Record<string, string> = {
  "active_route_has_no_steps": "Маршрут не содержит этапов",
  "active_route_not_found": "Не найден активный маршрут",
  "active_techcard_has_no_lines": "Техкарта не содержит операций",
  "active_techcard_not_found": "Не найдена активная техкарта для продукта",
  "auto_fallback": "Маршрут скорректирован автоматически — проверьте корректность",
  "duplicate_sku_due_date": "Дубликат строки Excel: такая же строка уже есть в плане.",
  "manual_route_inactive": "Ручной маршрут неактивен",
  "manual_route_not_found": "Ручной маршрут не найден",
  "no_route_candidate": "Не найден маршрут, удовлетворяющий правилам выбора",
  "product_inactive": "Продукт неактивен",
  "product_not_found": "Продукт не найден",
  "quantity_must_be_positive": "Количество должно быть положительным",
  "route_contains_excluded_step": "Маршрут содержит запрещенный правилами участок",
  "route_contains_inactive_section": "Маршрут содержит неактивный участок",
  "route_missing_pack_additional_operation": "В маршруте нет дополнительной операции упаковки",
  "route_missing_required_step": "В маршруте отсутствует обязательный этап",
  "route_not_found": "Не найден маршрут для позиции",
  "route_not_matching_import_signature": "Маршрут не совпадает с ожидаемым",
  "route_primary_operation_mismatch": "Основная операция маршрута не совпадает с импортированной. Проверьте соответствие техкарты и маршрута.",
  "route_rule_conflict": "Правила выбора маршрута конфликтуют",
  "route_sequence_invalid": "Неверная последовательность этапов в маршруте",
  "route_signature_incomplete": "Сигнатура маршрута позиции неполная",
  "selection_rules": "Маршрут выбран правилами",
}

// Лейблы предупреждений (warning codes)
export const warningLabels: Record<string, string> = {
  "hanger_quantity_not_set": "quantity_per_hanger не задан — количество не округлено",
  "paired_hanger_adjusted": "Округлено для компонента парной техкарты",
  "paired_hanger_mismatch": "Разное кол-во на подвес у компонентов парной техкарты",
  "paired_profile_product_unmapped": "Парный профиль не сопоставлен",
  "paired_row_auto_included": "Автодобавлена парная строка",
  "period_not_detected": "не определен",
  "product_name_missing": "Отсутствует наименование",
  "route_auto_fallback": "Маршрут скорректирован автоматически — проверьте корректность",
  "row_selection_applied": "Применён фильтр строк",
  "row_selection_auto_included": "Автодобавлены парные строки",
  "techcard_pair_not_resolved": "Не выбран парный профиль техкарты",
}

// Лейблы статуса валидации позиции
export const validationLabels: Record<string, string> = {
  "invalid": "Ошибка",
  "pending": "Ожидает",
  "valid": "Пройдена",
}

// Лейблы статусов задач участка
export const taskStatusLabels: Record<string, string> = {
  "blocked": "Блокировка",
  "cancelled": "Отменен",
  "completed": "Завершен",
  "done": "Завершен",
  "in_progress": "В работе",
  "in_work": "В работе",
  "partially": "Частично",
  "partially_completed": "Частично",
  "pending": "Ожидает",
  "waiting_previous": "Ожидает",
}

// Лейблы статусов этапов выполнения
export const stageStatusLabels: Record<string, string> = {
  "cancelled": "Отменён",
  "completed": "Выполнен",
  "in_progress": "В работе",
  "not_started": "Не начат",
  "partially_completed": "Частично выполнен",
  "ready": "Готов",
  "waiting_previous": "Ожидает этап",
}

// Лейблы статусов bulk-операций
export const bulkStatusLabels: Record<string, string> = {
  "failed": "Ошибка",
  "skipped": "Пропущено",
  "success": "Успешно",
}

// Лейблы действий изменения плана
export const actionLabels: Record<string, string> = {
  "add": "Добавить в список (add)",
  "cancel_draft_position": "Отменить",
  "create_position": "Создать",
  "exclude_section": "Исключить",
  "ignore_unchanged": "Без изменений",
  "mark_possible_duplicate": "Возможный дубль",
  "remove": "Удалить из списка (remove)",
  "require_section": "Добавить",
  "resolve_by_type": "Резолв по типу",
  "set": "Установить (set)",
  "set_operation": "Установить операцию",
  "update_draft_position": "Обновить",
}

// Переводы серверных ошибок (англ. фразы с плейсхолдерами {0}, {1}, ...) → RU
export const errorPhraseTranslations: Record<string, string> = {
  "Action references unknown section": "Действие ссылается на неизвестный участок",
  "Action references unknown section_code": "Действие ссылается на неизвестный section_code",
  "Approve failed: {0}": "Сбой утверждения: {0}",
  "At least one action is required": "Требуется хотя бы одно действие",
  "Attachment not found": "Вложение не найдено",
  "Cancelled release batch cannot be released": "Отменённая партия не может быть выпущена",
  "Cannot delete profile: it is used by route selection rules": "Нельзя удалить профиль: он используется правилами выбора маршрута",
  "Cannot rollback: position already released": "Нельзя откатить: позиция уже выпущена",
  "Change set does not belong to production plan": "Набор изменений не относится к плану производства",
  "Change set for batch not found": "Набор изменений для партии не найден",
  "Change set not found": "Набор изменений не найден",
  "Comment body must not be empty": "Текст комментария не должен быть пустым",
  "Complete quantity exceeds quantity in work": "Количество факта превышает объём «В работе»",
  "Component product not found": "Продукт-компонент не найден",
  "Condition field_path is required": "Требуется field_path у условия",
  "Condition value is required for {0}": "Для оператора {0} требуется значение условия",
  "Context condition field_path is required": "Требуется field_path у контекстного условия",
  "Corrected quantity exceeds transferable amount of source task. Available to transfer: {0}": "Скорректированное количество превышает доступный к передаче объём исходной задачи. Доступно к передаче: {0}",
  "Could not determine required headers from mapping": "Не удалось определить обязательные колонки из mapping",
  "Created plan position not found": "Созданная позиция плана не найдена",
  "DSL action path must start with 'ctx.'": "Путь действия DSL должен начинаться с «ctx.»",
  "Defect item not found": "Позиция брака не найдена",
  "Defect not found": "Брак не найден",
  "Either section_id or spg_id must be provided": "Необходимо указать section_id или spg_id",
  "Excel condition must define field_path or explicit excel column binding": "Условие Excel должно задавать field_path или явную привязку к колонке",
  "Excel sheet is empty": "Лист Excel пуст",
  "File content not available": "Содержимое файла недоступно",
  "File not found": "Файл не найден",
  "File not found on disk": "Файл не найден на диске",
  "Final release allowed only for final route stage": "Финальный выпуск разрешён только на финальном этапе маршрута",
  "Final release exceeds releasable quantity": "Финальный выпуск превышает доступный к выпуску объём",
  "Group code already exists for this section": "Код группы уже используется для этого участка",
  "Import batch not found": "Пакет импорта не найден",
  "Import template not found": "Шаблон импорта не найден",
  "Inactive section cannot be used in route": "Неактивный участок нельзя использовать в маршруте",
  "Inactive section {0}": "Неактивный участок {0}",
  "Insufficient permissions": "Недостаточно прав",
  "Invalid Excel file: {0}": "Некорректный файл Excel: {0}",
  "Invalid column_mapping JSON: {0}": "Некорректный JSON в column_mapping: {0}",
  "Invalid credentials": "Неверные учётные данные",
  "Invalid import_template_id": "Некорректный import_template_id",
  "Invalid profile_id": "Некорректный profile_id",
  "Invalid row number '{0}'": "Некорректный номер строки «{0}»",
  "Invalid row range '{0}'": "Некорректный диапазон строк «{0}»",
  "Invalid row range '{0}': end is less than start": "Некорректный диапазон строк «{0}»: конец меньше начала",
  "Invalid sort field: {0}": "Неизвестное поле сортировки: {0}",
  "Invalid sort order: {0}": "Неизвестный порядок сортировки: {0}",
  "Location id={0} not found": "Участок с id={0} не найден",
  "Location with id={0} not found": "Участок с id={0} не найден",
  "Manual pass failed at step {0}: {1}": "Сбой ручного пропуска на этапе {0}: {1}",
  "Next route step not found": "Следующий этап маршрута не найден",
  "No approved positions selected": "Не выбрано ни одной утверждённой позиции",
  "No excess quantity available for return": "Нет излишков для возврата на склад",
  "No plan position created for test run": "Для тестового прогона не создана позиция плана",
  "No route found for this product": "Для этого продукта не найден маршрут",
  "No route step found for this section in the plan position": "Для этого участка в позиции плана не найден этап маршрута",
  "No sections associated with this SPG": "С этой ГХП не связано ни одного участка",
  "No steps/stages added for route {0}. Built route has {1} steps.": "Для маршрута «{0}» не добавлено ни одного этапа. Построенный маршрут содержит {1} шагов.",
  "No tasks created for released position": "Для выпущенной позиции не создано ни одной задачи",
  "Only .zip files are accepted": "Принимаются только файлы .zip",
  "Only accepted transfers can be cancelled": "Отменять можно только принятые передачи",
  "Only accepted transfers can be corrected": "Корректировать можно только принятые передачи",
  "Only applied change sets can be rolled back": "Откатить можно только применённые наборы изменений",
  "Only approved positions can be released": "Выпускать можно только утверждённые позиции",
  "Only one final step allowed": "Допускается только один финальный этап",
  "Operation group not found": "Группа операций не найдена",
  "Operation not found in this section": "Операция не найдена в этом участке",
  "Plan position must be released": "Позиция плана должна быть выпущена",
  "Plan position not found": "Позиция плана не найдена",
  "Position #{0} has no route assigned": "Для позиции #{0} не назначен маршрут",
  "Position #{0}: no paired techcard found for product resolution": "Позиция #{0}: не найдена парная техкарта для резолюции продукта",
  "Position #{0}: paired techcard has no component products": "Позиция #{0}: парная техкарта не содержит компонентов",
  "Position already has execution facts; manual route pass is allowed only before execution starts": "По позиции уже есть факты выполнения; ручной пропуск маршрута разрешён только до начала выполнения",
  "Position does not belong to production plan": "Позиция не относится к плану производства",
  "Position has no route tasks": "У позиции нет задач маршрута",
  "Position has no tasks and cannot be released from current status": "У позиции нет задач, выпуск из текущего статуса невозможен",
  "Position not found": "Позиция не найдена",
  "Position status must be approved or released, got '{0}'": "Статус позиции должен быть «утверждена» или «выпущена», получено «{0}»",
  "Position with status '{0}' cannot be approved": "Позиция в статусе «{0}» не может быть утверждена",
  "Position {0} has no route assigned - cannot release without route": "Для позиции {0} не назначен маршрут — выпуск без маршрута невозможен",
  "PostgreSQL client tools недоступны, а контейнер {0} не запущен.": "PostgreSQL-утилиты недоступны, а контейнер {0} не запущен.",
  "Product not found": "Продукт не найден",
  "Production plan must be approved before release": "План производства должен быть утверждён перед выпуском",
  "Production plan not found": "План производства не найден",
  "Profile code is required": "Требуется код профиля",
  "Profile has no route_sections defined": "В профиле не определены route_sections",
  "Profile name is required": "Требуется название профиля",
  "Profile not found": "Профиль не найден",
  "Profile with this code already exists": "Профиль с таким кодом уже существует",
  "Quantities must be >= 0": "Количество должно быть >= 0",
  "Quantity must be positive": "Количество должно быть положительным",
  "Release batch has no positions": "В партии выпуска нет позиций",
  "Release batch not found": "Партия выпуска не найдена",
  "Release failed: {0}": "Сбой выпуска: {0}",
  "Release quantity exceeds approved remaining quantity": "Количество к выпуску превышает утверждённый остаток",
  "Release quantity must be > 0": "Количество к выпуску должно быть > 0",
  "Remainder already consumed": "Остаток уже израсходован",
  "Remainder not found": "Остаток не найден",
  "Required columns are missing: {0}": "Отсутствуют обязательные колонки: {0}",
  "Resolve quantity exceeds unresolved discrepancy": "Количество разрешения превышает неурегулированное расхождение",
  "Return quantity ({0}) exceeds available for return ({1})": "Количество возврата ({0}) превышает доступное к возврату ({1})",
  "Rework decisions require an associated work task": "Решения по доработке требуют привязанной рабочей задачи",
  "Rework task not found": "Задача на доработку не найдена",
  "Route contains inactive section": "Маршрут содержит неактивный участок",
  "Route for position {0} is not active": "Маршрут для позиции {0} не активен",
  "Route has no stages": "Маршрут не содержит этапов",
  "Route is inactive": "Маршрут не активен",
  "Route is not active": "Маршрут не активен",
  "Route not found": "Маршрут не найден",
  "Route sequence is invalid": "Неверная последовательность этапов маршрута",
  "Route stage not found": "Этап маршрута не найден",
  "Route with this name already exists": "Маршрут с таким именем уже существует",
  "Route {0} created without stages": "Маршрут «{0}» создан без этапов",
  "RouteStage {0} not found": "Этап маршрута {0} не найден",
  "Row number must be positive: '{0}'": "Номер строки должен быть положительным: «{0}»",
  "Row numbers must be positive in '{0}'": "Номера строк должны быть положительными в «{0}»",
  "Rule name is required": "Требуется название правила",
  "Rule not found": "Правило не найдено",
  "Rule with this code already exists": "Правило с таким кодом уже существует",
  "SKU '{0}' not found in database": "Артикул «{0}» не найден в базе данных",
  "SKU already exists": "Артикул уже используется",
  "SKU must not be empty": "Артикул не может быть пустым",
  "SPG ID does not exist": "ГХП с таким ID не существует",
  "SPG code already exists": "Код ГХП уже используется",
  "SPG not found": "ГХП не найдена",
  "Section code already exists": "Код участка уже используется",
  "Section does not belong to this SPG": "Участок не относится к этой ГХП",
  "Section is locked to single-window context": "Режим одного окна разрешает работу только с текущим участком",
  "Section is not bound to any SPG": "Участок не привязан ни к одной ГХП",
  "Section not found": "Участок не найден",
  "Section {0} not found": "Участок {0} не найден",
  "Selected plan position must be approved": "Выбранная позиция плана должна быть утверждена",
  "Selected plan position not found": "Выбранная позиция плана не найдена",
  "Sequence must be > 0": "Последовательность должна быть > 0",
  "Sheet index {0} not found": "Лист с индексом {0} не найден",
  "Some positions not found or belong to a different plan": "Некоторые позиции не найдены или относятся к другому плану",
  "Source task plan line not found": "Не найдена строка плана исходной задачи",
  "Target group does not exist": "Целевая группа не существует",
  "Target task has already consumed or issued parts. Cannot reduce transfer by {0} as target task only has {1} available stock": "Целевая задача уже использовала или выдала материалы. Нельзя уменьшить передачу на {0}, так как в целевой задаче доступно только {1}",
  "Task execution failed at step {0}: {1}": "Сбой выполнения задачи на этапе {0}: {1}",
  "Task must be in progress": "Задача должна быть в работе",
  "Task must be ready/in_progress/partially_completed": "Задача должна быть в статусе «готова», «в работе» или «частично завершена»",
  "Task not found": "Задача не найдена",
  "Techcard has no linked product": "У техкарты нет привязанного продукта",
  "Techcard has no product_id": "У техкарты не указан product_id",
  "Techcard is inactive": "Техкарта не активна",
  "Techcard not found": "Техкарта не найдена",
  "Techcard product not found": "Продукт техкарты не найден",
  "Template is inactive": "Шаблон не активен",
  "Template name is required": "Требуется название шаблона",
  "Template not found": "Шаблон не найден",
  "Template with this code already exists": "Шаблон с таким кодом уже существует",
  "Transfer discrepancy not found": "Расхождение по передаче не найдено",
  "Transfer failed at step {0}: {1}": "Сбой передачи на этапе {0}: {1}",
  "Transfer must be sent": "Передача должна быть отправлена",
  "Transfer not found": "Передача не найдена",
  "Transfer quantity exceeds transferable amount": "Количество передачи превышает доступный к передаче объём",
  "Transfer target must be next route step": "Получатель передачи должен быть следующим этапом маршрута",
  "Transfer tasks must belong to same plan position": "Задачи передачи должны принадлежать одной позиции плана",
  "Transfer tasks must have same product": "Задачи передачи должны относиться к одному продукту",
  "Transfers within the same Storage Production Group (GHP) are not allowed": "Передачи внутри одной группы хранения и производства (ГХП) запрещены",
  "Unable to create route tasks": "Не удалось создать задачи маршрута",
  "Unknown action type: {0}": "Неизвестный тип действия: {0}",
  "Unknown processing flag codes: {0}": "Неизвестные коды флагов обработки: {0}",
  "Unknown scenario_id '{0}'": "Неизвестный scenario_id «{0}»",
  "Unsupported Excel file extension: {0}": "Неподдерживаемое расширение Excel-файла: {0}",
  "User is disabled": "Пользователь отключён",
  "Workbook sheet is empty": "Лист книги пуст",
  "accepted + rejected exceeds sent quantity": "Сумма принятого и отклонённого превышает отправленное количество",
  "accepted + rejected must be > 0": "Принято + отклонено должно быть > 0",
  "accepted/rejected must be >= 0": "Принято/отклонено должно быть >= 0",
  "actual_quantity must be non-negative": "actual_quantity должно быть >= 0",
  "column_mapping must be a JSON object": "column_mapping должен быть JSON-объектом",
  "excel_column_index must be positive": "excel_column_index должен быть положительным",
  "excel_column_passport has duplicate index values": "В excel_column_passport есть дублирующиеся index",
  "excel_column_passport.field_path is required": "Требуется excel_column_passport.field_path",
  "excel_column_passport.header is required": "Требуется excel_column_passport.header",
  "excel_column_passport.index must be positive": "excel_column_passport.index должен быть положительным",
  "excel_column_passport.letter is required": "Требуется excel_column_passport.letter",
  "force=true is not allowed in production": "force=true запрещён в продакшне",
  "initial_quantity must be > 0": "initial_quantity должно быть > 0",
  "length_mm must be > 0, got {0}": "length_mm должно быть > 0, получено {0}",
  "operation_type must be 'in' or 'out'": "operation_type должен быть «in» или «out»",
  "original_filename is required": "Требуется original_filename",
  "position_ids must not be empty": "position_ids не должны быть пустыми",
  "product_id is required for manual defect registration": "Для ручной регистрации брака требуется product_id",
  "profiles.db not found in ZIP": "profiles.db не найден в архиве ZIP",
  "quantity must be positive": "Количество должно быть положительным",
  "route_build_error: {0}": "Ошибка построения маршрута: {0}",
  "row_selection has an empty segment": "В row_selection есть пустой сегмент",
  "row_selection must not be empty": "row_selection не должен быть пустым",
  "run_id '{0}' already exists. Each run_id must be unique.": "run_id «{0}» уже существует. Каждый run_id должен быть уникальным.",
  "section_id or route_stage_id is required for manual defect registration": "Для ручной регистрации брака требуется section_id или route_stage_id",
  "size_bytes must be > 0": "size_bytes должно быть > 0",
  "target_route_stage_id is required for 'to_step_ready' preset": "target_route_stage_id обязателен для пресета «to_step_ready»",
  "target_route_stage_id is required unless complete_route is true": "target_route_stage_id обязателен, если complete_route не равно true",
  "target_route_stage_id not found in route steps": "target_route_stage_id не найден среди этапов маршрута",
  "target_route_stage_id not found in this position route": "target_route_stage_id не найден в маршруте этой позиции",
  "template_id is required": "Требуется template_id",
  "{0} must be > 0": "{0} должно быть > 0",
  "{0} requires group_code": "{0} требует group_code",
  "{0} requires operation_code": "{0} требует operation_code",
  "{0} requires section_code": "{0} требует section_code",
  "{0} requires section_id": "{0} требует section_id",
  "Буфер обмена пуст": "Буфер обмена пуст",
  "Нет данных для импорта": "Нет данных для импорта",
}

// Лейблы качества остатков
export const qualityStateLabels: Record<string, string> = {
  "FINAL_SCRAP": "Окончательный брак",
  "GOOD": "Годный",
  "REWORK": "Переделка",
  "SCRAP": "Брак",
  "final_scrap": "Окончательный брак",
  "good": "Годный",
  "rework": "Переделка",
  "scrap": "Брак",
}

// Лейблы причин движения складских операций
export const stockReasonLabels: Record<string, string> = {
  "ADJUSTMENT_IN": "Корректировка +",
  "ADJUSTMENT_OUT": "Корректировка −",
  "COMPLETE": "Завершено",
  "FINAL_RELEASE": "Финальный выпуск",
  "ISSUE_TO_WORK": "Выдача в работу",
  "MANUAL_IN": "Ручной приход",
  "MANUAL_OUT": "Ручной расход",
  "RETURN_TO_PREVIOUS": "Возврат на предыдущий участок",
  "RETURN_TO_STOCK": "Возврат на склад",
  "REWORK": "Переделка",
  "SCRAP": "Списание в брак",
  "TRANSFER_RECEIVE": "Передача получено",
  "TRANSFER_SEND": "Передача отправлено",
  "adjustment_in": "Корректировка +",
  "adjustment_out": "Корректировка −",
  "complete": "Завершено",
  "final_release": "Финальный выпуск",
  "issue_to_work": "Выдача в работу",
  "manual_in": "Ручной приход",
  "manual_out": "Ручной расход",
  "return_to_previous": "Возврат на предыдущий участок",
  "return_to_stock": "Возврат на склад",
  "rework": "Переделка",
  "scrap": "Списание в брак",
  "transfer_receive": "Передача получено",
  "transfer_send": "Передача отправлено",
}

// Лейблы типов участков
export const sectionTypeLabels: Record<string, string> = {
  "finished_stock": "Склад готовой продукции",
  "production": "Производство",
  "raw_stock": "Склад сырья",
  "scrap": "Брак",
  "wip_stock": "Склад полуфабриката",
}

// Лейблы фаз правил выбора маршрута
export const rulePhaseLabels: Record<string, string> = {
  "normalize": "Нормализация",
  "resolve_operations": "Резолв операций",
  "resolve_signatures": "Резолв сигнатур",
  "route_select": "Выбор маршрута",
}

// Лейблы источников условий правил
export const ruleSourceLabels: Record<string, string> = {
  "ctx": "Контекст",
  "excel": "Колонки Excel",
  "payload": "Нормализованные поля",
  "product": "Поля продукта",
}

// Лейблы операторов условий правил
export const ruleOperatorLabels: Record<string, string> = {
  "contains": "содержит",
  "empty": "пусто",
  "equals": "равно",
  "in": "в списке",
  "not_contains": "не содержит",
  "not_empty": "не пусто",
  "not_equals": "не равно",
  "not_in": "не в списке",
  "regex": "regex",
}

// Лейблы кодов операций
export const operationCodeLabels: Record<string, string> = {
  "anodize": "анодирование",
  "cut": "порезка",
  "press_comb": "гребенка",
  "press_window": "окно",
}

// Лейблы названий цветов
export const colorNameLabels: Record<string, string> = {
  "black": "чёрный",
  "bronze": "бронза",
  "champagne": "шампань",
  "natural": "натуральный",
  "silver": "серебро",
}

// Лейблы хранилищ бэкапов
export const backupStorageLabels: Record<string, string> = {
  "imports": "Импорт",
  "products": "Продукты",
}

// Лейблы стадий бэкапа
export const backupStageLabels: Record<string, string> = {
  "adding_files": "Файлы",
  "analyzing": "Анализ",
  "completed": "Готово",
  "dumping_database": "База данных",
  "exporting_tables": "CSV-экспорт",
  "failed": "Ошибка",
  "preparing": "Подготовка",
  "queued": "Очередь",
  "writing_dump": "Архив",
  "writing_manifest": "Manifest",
}

// Лейблы типов бэкапов
export const backupTypeLabels: Record<string, string> = {
  "daily": "Ежедневный",
  "manual": "Вручную",
  "monthly": "Ежемесячный",
  "weekly": "Еженедельный",
}

// Каталог ролей: code -> (label, sections)
export interface RoleDef { code: string; label: string; sections: string[] }
export const roles: RoleDef[] = [
  { code: "admin", label: "Администратор", sections: ["/", "/references", "/planning", "/execution", "/section-tasks", "/transfers", "/spg", "/audit-logs", "/settings", "/settings/dev", "/dev"] },
  { code: "planner", label: "Планировщик", sections: ["/", "/references", "/planning", "/execution", "/section-tasks", "/transfers", "/spg", "/audit-logs", "/settings", "/dev"] },
  { code: "section_manager", label: "Начальник участка", sections: ["/", "/references", "/execution", "/section-tasks", "/transfers", "/spg", "/audit-logs", "/settings", "/dev"] },
  { code: "operator", label: "Оператор", sections: ["/", "/references", "/section-tasks", "/transfers", "/spg", "/audit-logs", "/settings", "/dev"] },
  { code: "viewer", label: "Наблюдатель", sections: ["/", "/references", "/section-tasks", "/spg", "/audit-logs", "/settings", "/dev"] },
  { code: "transporter", label: "Транспортировщик", sections: ["/", "/references", "/section-tasks", "/transfers", "/spg", "/audit-logs", "/settings", "/dev"] },
]
